### ISSUE TITLE
Type safety, family

### ISSUE THREAD

**Issue by rendaw** [keeperofdakeys/dns-lookup#20]
Thanks for this library!  I'm not sure why the standard library almost exposes this but then seems to go out of its way not to.

This is two combined issues:
1. The `family` hint is named `address` which doesn't match the documentation for getaddrinfo and is ordered differently from the documentation.  I was pretty worried this didn't support the family field or was based on some other function and I was confusing them.
2. All the hint fields are ints, so if you swap them there's no compile error. There are enums for these, but they don't seem to be used anywhere in the API.  Changing the hint fields to the enums then having the `as_addrinfo` automatically do the `into()` conversions would be easier and would result in a compile error if you accidentally swapped them.

**Comment by keeperofdakeys** [comment]
Hi, thanks for the feedback.

At this point I'm not going to rename the field. This would change the public api, causing unneeded churn for downstream users. I think reordering them should be fine (I'll need to look into this), and I'll update the documentation so it's clearer that it's actually address family.

Regarding ints for the hints field, this is intentional. Different libc implementations offer different socket types, address families etc, so it's hard to offer a single Enum that can be used for every libc. Instead of trying to track every libc implementation it's easier to offer the field as an int, and let the programmer worry about different libc implementations. So this crate worries about safety with regards to pointers and C-isms, while offering getaddrinfo (and friends) as directly as possible.

(There is a way around the above by using generics with Into - https://doc.rust-lang.org/std/convert/trait.Into.html#examples - I might have a look at how easy this is to implement, and if it's compatible with existing calls).

**Comment by keeperofdakeys** [comment]
I've pushed some changes to address these concerns.
