### ISSUE TITLE
NXDOMAIN vs SERVFAIL

### ISSUE THREAD

**Issue by Eilie** [keeperofdakeys/dns-lookup#7]
Hello, how to distinguish between NXDOMAIN and SERVFAIL? Currently for both cases `lookup_host ` returns `failed to lookup address information: Name or service not known`. For example bind9 tool named `host` returns  `2(SERVFAIL)` and `3(NXDOMAIN)` correctly.

**Comment by keeperofdakeys** [comment]
Unfortunately you can't at the moment. I'm not exposing this in any of my APIs, mainly so that I can use `std::io::Result` as the return type.

The C `getnameinfo` and `getaddrinfo` functions return `EAI_AGAIN` for `SERVFAIL`, and `EAI_NONAME` for `NXDOMAIN`. I might look into modifying these wrappers so that this information is passed along. However I don't plan on adding this to `lookup_host` or `lookup_addr`.

P.S. From my testing, the error string for a `SERVFAIL` should be returned as "Temporary failure in name resolution".

**Comment by keeperofdakeys** [comment]
I just wanted to drop an update on this issue. While I've implemented a solution for getting the specific failure, it's currently not compiling on OSX or BSD systems. Rust's libc is missing some re-exports of C symbols that I need but I hope to find a work around soon.

**Comment by keeperofdakeys** [comment]
The lastest release 0.9.0 should allow you to tell the difference between these on getaddrinfo and getnameinfo. Be aware that the returned error for NXDOMAIN and SERVFAIL can vary by platform.
